version: 2.1

jobs:
  deploy:
    docker:
      - image: cimg/node:16.20

    steps:
      - checkout

      - add_ssh_keys

      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@$HOST << 'EOF'
              export NVM_DIR="$HOME/.nvm"

              [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

              nvm use 16.20.2

              node -v
              npm -v

              cd ~/seo-app

              git pull

              cd server
              npm install

              cd ../client
              npm install
              npm run build

              pm2 restart backend
              pm2 restart frontend

              pm2 save
            EOF

workflows:
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
